Lab.EF/Lab.EF.MVC/Models/CustomerView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lab.EF.MVC.Models
{
    public class CustomerView
    {
        [Required(ErrorMessage = "debe ingresar el costumer id")]
        [StringLength(5)]
        [Display(Name = "Customer Id")]
        public string CustomerID { get; set; }

        [Required(ErrorMessage = "debe ingresar el nombre de la compañia")]
        [StringLength(40)]
        [Display(Name = "Company Name")]
        public string CompanyName { get; set; }

        [StringLength(30)]
        [Display(Name = "Contact Name")]
        public string ContactName { get; set; }

        [StringLength(30)]
        [Display(Name = "Contact Title")]
        public string ContactTitle { get; set; }

        [StringLength(60)]
        public string Address { get; set; }

        [StringLength(15)]
        public string City { get; set; }

        [StringLength(15)]
        public string Region { get; set; }

        [StringLength(15)]
        public string Country { get; set; }

        [StringLength(24)]
        public string Phone { get; set; }

    }
}

Lab.EF/Lab.EF.MVC/Models/ProductView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lab.EF.MVC.Models
{
    public class ProductView
    {
        [Display(Name = "Product Id")]
        public int ProductID { get; set; }

        [Required(ErrorMessage = "debe ingresar un nombre")]
        [StringLength(40)]
        [Display(Name = "Product Name")]
        public string ProductName { get; set; }

        [Display(Name = "Supplier Id")]
        public int? SupplierID { get; set; }

        [Display(Name = "Category Id")]
        public int? CategoryID { get; set; }

        [StringLength(20)]
        [Display(Name = "Quantity Per Unit")]
        public string QuantityPerUnit { get; set; }

        [Display(Name = "Unit Price")]
        public decimal? UnitPrice { get; set; }

        [Display(Name = "Units In Stock")]
        public short? UnitsInStock { get; set; }


    }
}

Lab.EF/Lab.EF.MVC/Controllers/CustomerController.cs
using Lab.EF.Entities;
using Lab.EF.Logic;
using Lab.EF.MVC.Models;
using Lab.EF.Services;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Lab.EF.MVC.Controllers
{
    public class CustomerController : Controller
    {
        private CustomerService _customerService = new CustomerService();

        public async Task<ActionResult> Index()
        {
            try
            {
                List<Customers> customers = await _customerService.GetAll();

                List<CustomerView> customersViews = customers.Select(c => new CustomerView
                {
                    CustomerID = c.CustomerID,
                    Address = c.Address,
                    Phone = c.Phone,
                    City = c.City,
                    CompanyName = c.CompanyName,
                    ContactName = c.ContactName,
                    ContactTitle = c.ContactTitle,
                    Country = c.Country,
                    Region = c.Region

                }).ToList();

                return View(customersViews);
            }
            catch(Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }
           
        }

        public ActionResult Create()
        {
           
            return View();
        }


        [HttpPost]
        public ActionResult Create(CustomerView customerView)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    Customers customer = new Customers
                    {
                        CustomerID = customerView.CustomerID,
                        Address = customerView.Address,
                        Phone = customerView.Phone,
                        City = customerView.City,
                        CompanyName = customerView.CompanyName,
                        ContactName = customerView.ContactName,
                        ContactTitle = customerView.ContactTitle,
                        Country = customerView.Country,
                        Region = customerView.Region
                    };

                    _customerService.Add(customer);
                    TempData["message"] = "customer created succesfully!";
                    return RedirectToAction("Index");
                }
                return View();

            }
            catch(Exception ex)
            {
                return RedirectToAction("Index","Error");
            }

        }

        //[HttpDelete]
        public ActionResult Delete(string id)
        {
            try
            {
                _customerService.DeleteByString(id);
                TempData["message"] = "customer deleted succesfully!";
                return RedirectToAction("Index");
            }
            catch(DbUpdateException ex)
            {
                return RedirectToAction("DeleteCustomer","Error");
            }
            catch(Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }
        }

        public async Task<ActionResult> Edit(string id)
        {
            try
            {
                var customer = await _customerService.GetByIdString(id);

                var customerView = new CustomerView
                {
                    CustomerID = customer.CustomerID,
                    Address = customer.Address,
                    City = customer.City,
                    CompanyName = customer.CompanyName,
                    ContactName = customer.ContactName,
                    ContactTitle = customer.ContactTitle,
                    Country = customer.Country,
                    Phone = customer.Phone,
                    Region = customer.Region
                };

                return View(customerView);

            }
            catch(Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }

        }

        //[HhtpPut]
        [HttpPost]
        public ActionResult Edit(CustomerView customerView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Customers customer = new Customers
                    {
                        CustomerID = customerView.CustomerID,
                        Address = customerView.Address,
                        Phone = customerView.Phone,
                        City = customerView.City,
                        CompanyName = customerView.CompanyName,
                        ContactName = customerView.ContactName,
                        ContactTitle = customerView.ContactTitle,
                        Country = customerView.Country,
                        Region = customerView.Region
                    };

                    _customerService.Update(customer);
                    TempData["message"] = "customer edited succesfully!";
                    return RedirectToAction("Index");
                }
                return View();

            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }

        }
    }
}

Lab.EF/Lab.EF.MVC/Controllers/EmployeeController.cs
using Lab.EF.Entities;
using Lab.EF.Logic;
using Lab.EF.MVC.Models;
using Lab.EF.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Lab.EF.MVC.Controllers
{
    public class EmployeeController : Controller
    {
        private IService<Employees> _employeeService = new EmployeeService();

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> GetAll()
        {
            List<Employees> employees = await _employeeService.GetAll();

            List<EmployeeView> employeesViews = employees.Select(e => new EmployeeView
            {
                EmployeeID = e.EmployeeID,
                BirthDate = e.BirthDate,
                City = e.City,
                FirstName = e.FirstName,
                HireDate = e.HireDate,
                HomePhone = e.HomePhone,
                LastName = e.LastName,
                Region = e.Region,
                ReportsTo = e.ReportsTo,
                Title = e.Title

            }).ToList();

            return Json(employeesViews, JsonRequestBehavior.AllowGet);
        }
      
        
    }
}

Lab.EF/Lab.EF.MVC/Controllers/OrderController.cs
using Lab.EF.Entities;
using Lab.EF.Logic;
using Lab.EF.MVC.Models;
using Lab.EF.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Lab.EF.MVC.Controllers
{
    public class OrderController : Controller
    {
        private IService<Orders> _orderService = new OrderService();
        public string draw = "";
        public string start = "";
        public string length = "";
        public int pageSize, skip, recordsTotal;

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> GetAll()
        {
            List<Orders> orders = await _orderService.GetAll();

            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
;

            pageSize = length != null ? Convert.ToInt32(length) : 0;
            skip = start != null ? Convert.ToInt32(start) : 0;
            recordsTotal = 0;

            List<OrderView> ordersViews = orders.Select(o => new OrderView
            {
                      OrderID = o.OrderID,
                      CustomerID = o.CustomerID,
                      EmployeeID = o.EmployeeID,
                      Freight = o.Freight,
                      OrderDate = o.OrderDate,
                      RequiredDate = o.RequiredDate,
                      ShipCity = o.ShipCity,
                      ShipCountry = o.ShipCountry,
                      ShipName = o.ShipName,
                      ShippedDate = o.ShippedDate,
                      ShipVia = o.ShipVia 

            }).ToList();

            recordsTotal = ordersViews.Count();
            ordersViews = ordersViews.Skip(skip).Take(pageSize).ToList();

            return Json(new {draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal,
                            data = ordersViews});
            
        }
    }
}

Lab.EF/Lab.EF.MVC/Controllers/ProductController.cs
using Lab.EF.Entities;
using Lab.EF.Logic;
using Lab.EF.Logic.Repositories;
using Lab.EF.MVC.Models;
using Lab.EF.Services;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Lab.EF.MVC.Controllers
{
    public class ProductController : Controller
    {
        private IService<Products> _productService = new ProductService();
        public async Task<ActionResult> Index()
        {
            try
            {
                List<Products> products = await _productService.GetAll();

                List<ProductView> productsViews = products.Select(p => new ProductView
                {
                     ProductID = p.ProductID,
                     CategoryID = p.CategoryID,
                     ProductName = p.ProductName,
                     QuantityPerUnit = p.QuantityPerUnit,
                     SupplierID = p.SupplierID,
                     UnitPrice = p.UnitPrice,
                     UnitsInStock = p.UnitsInStock 

                }).ToList();

                return View(productsViews);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }
        }
        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Create(ProductView productView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Products product = new Products
                    {
                         ProductID = productView.ProductID,
                         ProductName = productView.ProductName,
                         CategoryID = productView.CategoryID,
                         QuantityPerUnit = productView.QuantityPerUnit,
                         UnitsInStock = productView.UnitsInStock,
                         SupplierID = productView.SupplierID,
                         UnitPrice = productView.UnitPrice,

                    };

                    _productService.Add(product);
                    TempData["message"] = "product created succesfully!";
                    return RedirectToAction("Index");
                }
                return View();

            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }

        }

        //[HttpDelete]
        public ActionResult Delete(int id)
        {
            try
            {
                _productService.Delete(id);
                TempData["message"] = "product deleted succesfully!";
                return RedirectToAction("Index");
            }
            catch (DbUpdateException ex)
            {
                return RedirectToAction("DeleteProduct", "Error");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            try
            {
                var product = await _productService.GetById(id);

                var productView = new ProductView
                {
                     ProductID = product.ProductID,
                     CategoryID = product.CategoryID,
                     ProductName = product.ProductName,
                     QuantityPerUnit = product.QuantityPerUnit,
                     SupplierID = product.SupplierID,
                     UnitPrice = product.UnitPrice,
                     UnitsInStock = product.UnitsInStock 

                };

                return View(productView);

            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }

        }

        [HttpPost]
        public ActionResult Edit(ProductView productView )
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Products product = new Products
                    {
                        ProductID = productView.ProductID,
                        ProductName = productView.ProductName,
                        CategoryID = productView.CategoryID,
                        QuantityPerUnit = productView.QuantityPerUnit,
                        UnitsInStock = productView.UnitsInStock,
                        SupplierID = productView.SupplierID,
                        UnitPrice = productView.UnitPrice,

                    };

                    _productService.Update(product);
                    TempData["message"] = "product edited succesfully!";
                    return RedirectToAction("Index");
                }
                return View();

            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }

        }
    }
}

Lab.EF/Lab.EF.MVC/Controllers/RegionController.cs
using Lab.EF.Entities;
using Lab.EF.Logic;
using Lab.EF.Logic.Repositories;
using Lab.EF.MVC.Models;
using Lab.EF.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Lab.EF.MVC.Controllers
{
    public class RegionController : Controller
    {
        private IService<Region> _regionService = new RegionService();
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> GetAll()
        {
            List<Region> regions = await _regionService.GetAll();

            var regionsViews = regions.Select(r => new RegionView
            {
                 RegionID = r.RegionID,
                 RegionDescription = r.RegionDescription,

            }).ToList();

            return Json(regionsViews, JsonRequestBehavior.AllowGet);
        }

    }
}

Lab.EF/Lab.EF.MVC/Controllers/ShipperController.cs
using Lab.EF.Entities;
using Lab.EF.Logic;
using Lab.EF.MVC.Models;
using Lab.EF.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Lab.EF.MVC.Controllers
{
    public class ShipperController : Controller
    {
        private IService<Shippers> _shipperService = new ShipperService();

        public ActionResult Index()
        {
            return View();
        }
        
        [HttpGet]
        public  async Task<JsonResult> GetAll()
        {
            List<Shippers> shippers =  await _shipperService.GetAll();

            var shippersViews =  shippers.Select(s => new ShipperView
            {
                ShipperID = s.ShipperID,
                CompanyName = s.CompanyName,
                Phone = s.Phone

            }).ToList();

            return Json(shippersViews,JsonRequestBehavior.AllowGet);
        }
        
      
    }
}

Lab.EF/Lab.EF.MVC/Views/Shared/_Categories.cshtml
@model Lab.EF.MVC.Models.CategoryView


<div class="container">
    <div class="col-md-6 col-md-offset-3">
        <div class="form-group">
            @Html.LabelFor(c => c.CategoryName, new { @class = "control-label  " })
            @Html.TextBoxFor(c => c.CategoryName, new { @class = "form-control input-lg", maxlength = "15" })
            @Html.ValidationMessageFor(c => c.CategoryName, "", new { @class = "text-danger " })
        </div>

        <div class="form-group">
            @Html.LabelFor(c => c.Description, new { @class = "control-label " })
            @Html.TextBoxFor(c => c.Description, new { @class = "form-control input-lg", maxlength = "30" })
            @Html.ValidationMessageFor(c => c.Description)
        </div>
        <div class="form-group ">
            @Html.ActionLink("Back", "Index", "Category", new { @class = "btn btn-lg btn-danger col-md-offset-2" })
            <input type="submit" class="btn btn-lg btn-success col-md-offset-2" value="Save" onclick = "return confirm('seguro desea guardar?');">
        </div>
    </div>
</div>
    

Lab.EF/Lab.EF.MVC/Views/Shared/_Customers.cshtml
@model Lab.EF.MVC.Models.CustomerView

<div class="container">   
    <div class="col-md-6 col-md-offset-3">
        <div class="form-group">
            @Html.LabelFor(c => c.CustomerID, new { @class = "control-label" })
            @Html.TextBoxFor(c => c.CustomerID, new { @class = "form-control input-lg", maxlength = "5" })
            @Html.ValidationMessageFor(c => c.CustomerID, "", new { @class = "text-danger " })
        </div>
        <div class="form-group">
            @Html.LabelFor(c => c.CompanyName, new { @class = "control-label" })
            @Html.TextBoxFor(c => c.CompanyName, new { @class = "form-control input-lg", maxlength = "40" })
            @Html.ValidationMessageFor(c => c.CompanyName, "", new { @class = "text-danger " })
        </div>
        <div class="form-group">
            @Html.LabelFor(c => c.ContactName, new { @class = "control-label" })
            @Html.TextBoxFor(c => c.ContactName, new { @class = "form-control input-lg", maxlength = "30" })
            @Html.ValidationMessageFor(c => c.ContactName)
        </div>
        <div class="form-group">
            @Html.LabelFor(c => c.ContactTitle, new { @class = "control-label" })
            @Html.TextBoxFor(c => c.ContactTitle, new { @class = "form-control input-lg", maxlength = "30" })
            @Html.ValidationMessageFor(c => c.ContactTitle)
        </div>
        <div class="form-group">
            @Html.LabelFor(c => c.Address, new { @class = "control-label" })
            @Html.TextBoxFor(c => c.Address, new { @class = "form-control input-lg", maxlength = "60" })
            @Html.ValidationMessageFor(c => c.Address)
        </div>
        <div class="form-group">
            @Html.LabelFor(c => c.City, new { @class = "control-label" })
            @Html.TextBoxFor(c => c.City, new { @class = "form-control input-lg", maxlength = "15" })
            @Html.ValidationMessageFor(c => c.City)
        </div>
        <div class="form-group">
            @Html.LabelFor(c => c.Region, new { @class = "control-label" })
            @Html.TextBoxFor(c => c.Region, new { @class = "form-control input-lg", maxlength = "15" })
            @Html.ValidationMessageFor(c => c.Region)
        </div>
        <div class="form-group">
            @Html.LabelFor(c => c.Country, new { @class = "control-label" })
            @Html.TextBoxFor(c => c.Country, new { @class = "form-control input-lg", maxlength = "15" })
            @Html.ValidationMessageFor(c => c.Country)
        </div>
        <div class="form-group">
            @Html.LabelFor(c => c.Phone, new { @class = "control-label" })
            @Html.TextBoxFor(c => c.Phone, new { @class = "form-control input-lg", maxlength = "24" })
            @Html.ValidationMessageFor(c => c.Phone)
        </div>
        <div class="form-group">

            @Html.ActionLink("Back", "Index", "Customer", new { @class = "btn btn-lg btn-danger col-md-offset-2" })
            <input type="submit" class="btn btn-lg btn-success col-md-offset-2" value="Save" onclick = "return confirm('seguro desea guardar?');">

        </div>
    </div>
</div>

Lab.EF/Lab.EF.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - NorthWind Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
</head>
<body class="bg-info">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                    <li>@Html.ActionLink("Customers", "Index", "Customer")</li>
                    <li>@Html.ActionLink("Customer Demographics", "Index", "CustomerDemographic")</li>
                    <li>@Html.ActionLink("Employees", "Index", "Employee")</li>
                    <li>@Html.ActionLink("Orders", "Index", "Order")</li>
                    <li>@Html.ActionLink("Order Details", "Index", "OrderDetail")</li>
                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                    <li>@Html.ActionLink("Regions", "Index", "Region")</li>
                    <li>@Html.ActionLink("Shippers", "Index", "Shipper")</li>
                    <li>@Html.ActionLink("Suppliers", "Index", "Supplier")</li>
                    <li>@Html.ActionLink("Territories", "Index", "Territory")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - NorthWind Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
  
    @RenderSection("scripts", required: false)
</body>
</html>

Lab.EF/Lab.EF.MVC/Views/Shared/_Products.cshtml
@model Lab.EF.MVC.Models.ProductView

<div class="container">
    <div class="col-md-6 col-md-offset-3">
        <div class="form-group">
            @Html.LabelFor(p => p.ProductName, new { @class = "control-label" })
            @Html.TextBoxFor(p => p.ProductName, new { @class = "form-control input-lg", maxlength = "40" })
            @Html.ValidationMessageFor(p => p.ProductName, "", new { @class = "text-danger " })
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.SupplierID, new { @class = "control-label" })
            @Html.TextBoxFor(p => p.SupplierID, new { @class = "form-control input-lg" })
            @Html.ValidationMessageFor(p => p.SupplierID, "", new { @class = "text-danger " })
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.CategoryID, new { @class = "control-label" })
            @Html.TextBoxFor(p => p.CategoryID, new { @class = "form-control input-lg" })
            @Html.ValidationMessageFor(p => p.CategoryID, "", new { @class = "text-danger " })
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.QuantityPerUnit, new { @class = "control-label" })
            @Html.TextBoxFor(p => p.QuantityPerUnit, new { @class = "form-control input-lg", maxlength = "20" })
            @Html.ValidationMessageFor(p => p.QuantityPerUnit, "", new { @class = "text-danger " })
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.UnitPrice, new { @class = "control-label" })
            @Html.TextBoxFor(p => p.UnitPrice, new { @class = "form-control input-lg" })
            @Html.ValidationMessageFor(p => p.UnitPrice, "", new { @class = "text-danger " })
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.UnitsInStock, new { @class = "control-label" })
            @Html.TextBoxFor(p => p.UnitsInStock, new { @class = "form-control input-lg" })
            @Html.ValidationMessageFor(p => p.UnitsInStock, "", new { @class = "text-danger " })
        </div>
        <div class="form-group">
            @Html.ActionLink("Back", "Index", "Product", new { @class = "btn btn-lg btn-danger col-md-offset-2" })
            <input type="submit" class="btn btn-lg btn-success col-md-offset-2" value="Save" onclick="return confirm('seguro desea guardar?');">

        </div>
    </div>
</div>